config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "games#index"

  resources :games, :only => [:index, :new, :show ] do
    resources :players, :only => [:show] do
      resources :moves, :only => [:new]
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  belongs_to :turn, :class_name => :Player, :foreign_key => "turn_id"
  belongs_to :winner, :class_name => :Player, :foreign_key => "winner_id"

  after_initialize :add_players

  def add_players
    if self.new_record?
      self.players << [Player.new(name:'muffin'), Player.new(name:'wombat')]
      self.turn = self.players.first
    end
  end

end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :player
  belongs_to :game

  after_create :next_turn

  def next_turn
    game.turn = game.players.select{|x| x.id != player.id }.first
    game.save
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game

  def my_turn
    id == game.turn.id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  realtime_controller({:queue => :redis}) # instruct all requests to enable realtime support via redis

  def realtime_user_id
    return current_user.id if current_user
  end

  def realtime_server_url
    # point this to your node.js-socket.io-redis/zmq realtime server (you can set this later)
    return 'http://localhost:5001'
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @game = Game.where.not(winner_id: nil).last
    redirect_to @game if @game
  end

  def new
    @game = Game.new
    if @game.save
      redirect_to @game
    else
      redirect_to :index
    end
  end

  def show
    @game = Game.find(params[:id])
    respond_to do |format|
      format.json do
        render :text => @game.to_json
      end
      format.any
    end

  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  def new
    @move = Move.create(game_id:params[:game_id], player_id: params[:player_id])
    @move.next_turn
    message = {
        :msg => {
            :current_turn => @move.game.turn_id
        },
        :recipient_user_ids => @move.game.players.collect(&:id)
    }
    $redis.publish 'realtime_msg', message.to_json
    render json: nil, status: :ok
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    @player = Player.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/index.html.erb
<h1>Battleship</h1>

<%= link_to "Wanna Play?", new_game_path %>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<% @game.players.each do | player | %>
  <%= link_to player.name, game_player_path(@game, player) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battleship</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- required: realtime support framework -->
  <%= realtime_support %>
  <!-- optional: message_handler dequeues realtime messages into Backbone.js style events -->
  <%= realtime_message_handler %>
  <!-- optional: message_console_logger listens or dequeues realtime messages to the browser console -->
  <%= realtime_message_console_logger %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/players/_game.html.erb
<%= link_to "Move #{game.turn.name}", new_game_player_move_path(game, game.turn) %>

app/views/players/show.html.erb
Welcome <%= @player.name %>
<div ng-app='app.battleshipApp' ng-controller='MoveCtrl' ng-init="init(<%= @player.id %>, <%= @player.game.id %>)">
  <p>{{ welcome }}</p>
  <div ng-show='myTurn'>
    <a href="" ng-click="makeMove()">
      Move <%= @player.name %>
    </a>
  </div>
</div>